-- 文章表
create table if not exists article
(
    id                   bigint auto_increment comment 'id' primary key,
    taskId               varchar(64)                        not null comment '任务 ID（UUID）',
    userId                bigint                             not null comment '用户 ID',
    topic                 varchar(500)                       not null comment '选题',
    userDescription       text                               null comment '用户补充描述',
    enabledImageMethods   json                               null comment '允许的配图方式列表（JSON 格式）',
    style                 varchar(50)                        null comment '文章风格：tech/emotional/educational/humorous',
    mainTitle             varchar(200)                       null comment '主标题',
    subTitle              varchar(300)                       null comment '副标题',
    titleOptions          json                               null comment '标题方案列表（JSON 格式）',
    outline               json                               null comment '大纲（JSON 格式）',
    content               text                               null comment '正文（Markdown 格式）',
    fullContent           text                               null comment '完整图文（Markdown 格式，含图片）',
    coverImage            varchar(512)                       null comment '封面图 URL',
    images                json                               null comment '配图列表（JSON 数组，包含封面图 position=1）',
    status                varchar(20) default 'PENDING'      not null comment '状态：PENDING/PROCESSING/COMPLETED/FAILED',
    phase                 varchar(50)                        null comment '当前阶段',
    errorMessage          text                               null comment '错误信息',
    createTime            datetime    default CURRENT_TIMESTAMP not null comment '创建时间',
    completedTime         datetime                           null comment '完成时间',
    updateTime            datetime    default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    isDelete              tinyint     default 0              not null comment '是否删除',
    UNIQUE KEY uk_taskId (taskId),
    INDEX idx_userId (userId),
    INDEX idx_status (status),
    INDEX idx_createTime (createTime),
    INDEX idx_userId_status (userId, status)
) comment '文章表' collate = utf8mb4_unicode_ci;
